### ISSUE TITLE
Add endpoint/service to return response of a mentioned size.

### ISSUE THREAD

**Issue by pranaytripathi** [maruina/go-infrabin#307]
# Summary

We are trying to test how the service responds when it has a large payload to return. This specifically replicates serving of an artifact such as a JS file, image etc.  It will be a good feature to have to test out larger payloads. 

HTTPbin also supports this feature 
https://httpbin.org/#/Dynamic_data/get_bytes__n_

##Example 

`curl -X GET "https://infrabin/bytes/32"`

This would return 32 bytes of random generated data.

I am up for picking this change up and contributing to the repository.

**Comment by maruina** [comment]
Hey @pranaytripathi, I'm very happy if you want to contribute with this feature :)

**Comment by pranaytripathi** [comment]
#311
