### ISSUE TITLE
Use Viper for config

### ISSUE THREAD

**Issue by Smirl** [maruina/go-infrabin#42]
# Summary

There are a few command line flags and environment variables used to configure `go-infrabin`. These are passed around in different ways:
- the `infrabin.Config` object
- directly from environment variables
- hard coded ports

It would be quite easy to allow Config files, Env vars, and cli flags using the cobra/viper set up.

# DOD

- ~use cobra for main.go~
- use viper in config.go
- all current config is via the above
- add options for binding ports (optional)

**Comment by Spedge** [comment]
I've used some of spf13's libraries before - in particular, viper for config. https://github.com/specialedge/hangar-api

Been a while though, but will give it a bash. If you need this done quickly, get someone else :P

Might suggest splitting out the command line work and the config file work?

**Comment by Smirl** [comment]
Sure, feel free to take it 🥇 . I will change this ticket just to Viper and create a new one for Cobra.

**Comment by Spedge** [comment]
Submitted #50 for review

**Comment by maruina** [comment]
Thanks @Spedge for your contribution!
