### ISSUE TITLE
Use Cobra for the CLI

### ISSUE THREAD

**Issue by Smirl** [maruina/go-infrabin#45]
# Summary

In https://github.com/maruina/go-infrabin/issues/42 we plan to use Viper for config.
This has an easy integration with Cobra to bind flags to the config.

**Comment by Spedge** [comment]
Hey, to confirm - are you looking for just flags to allow modification of the existing possible configuration items? 

For example _go-infrabin --grpc.port=6766 --admin.port=6376_

Or is it something more elaborate than that?
